baseurl         = "https://elv8.co"
theme           = "casper-two"
languageCode    = "en-US"
disqusShortname = "elv8"
paginate        = 6
#SectionPagesMenu = "main"
canonifyurls    = true

[params]
  title       = "Elv8.co Blog"
  subtitle    = "Technology, Management and Product"
  copyright   = "© 2018"

  cover       = "/images/default-image.jpg"
  description = "My Blog about Technology, Management and Product"
  metaDescription = ""
  #googleAnalytics = ""
  #customCSS = []
  #RSSLink = ""
  showSubscribe = false

  twitterName = "dudil"
  fbName = ""
  githubName = "dudil"
  linkedinName = "dudile"
  mediumName = ""
  showSupport = false

  logo = ""
  orgName = "Elv8.co"
  orgWebsite = "/about/"
  orgDescription = ""

  author = "Dudi Levy"
  authorAvatar = "images/profile.jpeg"
  authorLocation = "Tel Aviv, Israel"
  authorWebsite = "https://elv.co/about/"
  authorDescription = "I write about technology, tools, platforms and what you could do with them."

  pageNotFoundTitle = "404 - Page not found"

  #casper or caspertwo
  singleViewStyle = "casper"

[blackfriday]
  hrefTargetBlank = true

[permalinks]
  post = "/post/:slug/"

[[menu.main]]
  name = "Home"
  url = "/"
  weight = 200

[[menu.main]]
  name = "Articles"
  url = "/post/"
  weight = 190

[[menu.main]]
  name = "About"
  url = "/about/"
  Weight = 100